"""add group type

Revision ID: d559446e7a54
Revises: 3df075258449
Create Date: 2026-04-29 23:25:38.252223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd559446e7a54'
down_revision: Union[str, Sequence[str], None] = '3df075258449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_groups', schema=None) as batch_op:
        batch_op.drop_column('group_type')

    # ### end Alembic commands ###
